#!/usr/bin/env ruby

require "date"

if ARGV.empty?
  p "Usage: ./new post-title"
  exit 1
end

original_filename = ARGV[0]
til = ARGV[1] === "--til"
today = Date.today.strftime("%Y-%m-%d")
path = if til
  File.join("content/til", "#{today}-#{original_filename}.md")
else
  File.join("content/words", "#{today}-#{original_filename}.md")
end

File.open(path, "w") do |f|
  f.puts "---"
  f.puts "title: REPLACE ME"
  f.puts "date: #{today}"
  f.puts "description: |"
  f.puts "  FILL ME IN"
  f.puts "---"
end

p "Created: #{path}"
